import { useState, useEffect } from 'react';
import './Popup.css';

export const Popup = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext';

  const [currentUrl, setCurrentUrl] = useState('');

  useEffect(() => {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs.length > 0) {
        setCurrentUrl(tabs[0].url);
      }
    });
  }, []);

  const handleSummarize = () => {
    alert('📝 요약 버튼 클릭됨!');
    // TODO: 현재 탭에서 텍스트 추출 후 GPT API 호출
  };

  const handleTTS = () => {
    alert('🔊 TTS 실행!');
    // TODO: 요약된 텍스트를 TTS로 재생
  };

  return (
    <main>
      <h3>Popup Page</h3>      

      <div className="actions">
        <button className="action-button" onClick={handleSummarize}>
          📝 요약하기
        </button>
        <button className="action-button" onClick={handleTTS}>
          🔊 TTS 실행
        </button>
      </div>
      <h3>현재 탭 URL</h3>
            <p style={{ fontSize: '1rem', wordBreak: 'break-all' }}>{currentUrl}</p>
      <a href={link} target="_blank" rel="noreferrer">
        generated by create-chrome-ext
      </a>
    </main>
  );
};

export default Popup;
