import styled from 'styled-components'
import { SummaryBox } from '../components/SummaryBox'
import { useCurrentTabUrl } from '../hooks/useCurrentTabUrl'
import { useGptSummary } from '../hooks/useGptSummary'

const Container = styled.main`
  text-align: center;
  padding: 2rem;
  margin: 0 auto;
  font-size: 1.25rem;
  line-height: 1.6;
`

const Title = styled.h3`
  color: #007acc;
  text-transform: uppercase;
  font-size: 1rem;
  font-weight: bold;
  line-height: 2.4rem;
  margin: 2rem auto;
`

const Actions = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 2rem 0;
  gap: 1rem;
`

const Button = styled.button`
  background-color: #007acc;
  color: white;
  border: none;
  border-radius: 0.5rem;
  padding: 1rem 2rem;
  font-size: 1.25rem;
  cursor: pointer;
  width: 85%;
  max-width: 300px;
  transition: background-color 0.2s ease-in-out;

  &:hover {
    background-color: #005999;
  }

  &:focus {
    outline: 3px solid #ffffff;
    outline-offset: 2px;
  }
`

const Link = styled.a`
  font-size: 1rem;
  margin: 1rem;
  color: #666666;
  text-decoration: none;
  display: inline-block;

  &:hover {
    color: #007acc;
  }
`

const UrlText = styled.p`
  font-size: 1rem;
  word-break: break-all;
`

export const Popup = () => {
  const currentUrl = useCurrentTabUrl()
  const { summary, showSummary, fetchSummaryFromStorage, speakSummary } = useGptSummary()

  return (
    <Container>
      <Title>FISA Google Chrome Extension</Title>

      <Actions>
        <Button onClick={fetchSummaryFromStorage}>📝 요약하기</Button>
        <Button onClick={speakSummary}>🔊 TTS 실행</Button>
      </Actions>

      <Title>현재 탭 URL</Title>
      <UrlText>{currentUrl}</UrlText>

      {showSummary && summary && <SummaryBox title={summary.title} summary={summary.summary} />}

      <Link href="https://github.com/guocaoyi/create-chrome-ext" target="_blank" rel="noreferrer">
        generated by create-chrome-ext
      </Link>
    </Container>
  )
}

export default Popup
