import { useState, useEffect } from 'react'
import FontSizeToggle from '../components/FontSizeToggle';
import './SidePanel.css'
import { fontSizes, fontSizeMap } from '../constants/fontSizes';

export const SidePanel = () => {
  const link = 'https://github.com/guocaoyi/create-chrome-ext'

  const [currentUrl, setCurrentUrl] = useState('');

   const fetchCurrentTabUrl = () => {
    chrome.tabs.query({ active: true, currentWindow: true }, (tabs) => {
      if (tabs.length > 0) {
        setCurrentUrl(tabs[0].url);
      }
    });
  };

  const [fontSizeLevel, setFontSizeLevel] = useState('medium');
  const fontSizeStyle = {
    fontSize: fontSizeMap[fontSizeLevel],
  };

  useEffect(() => {
    // 컴포넌트 로드시 URL 가져오기
    fetchCurrentTabUrl();

    // 탭 전환 시 감지
    chrome.tabs.onActivated.addListener(fetchCurrentTabUrl);

    // 탭 업데이트(페이지 변경 등) 감지
    chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
      if (tab.active && changeInfo.url) {
        setCurrentUrl(changeInfo.url);
      }
    });
    // TODO: 요약중에 탭을 바꿀경우?

    // 클린업
    return () => {
      chrome.tabs.onActivated.removeListener(fetchCurrentTabUrl);
      chrome.tabs.onUpdated.removeListener(() => {}); // 안전한 클린업
    };
  }, []);

  const handleSummarize = () => {
    console.log(currentUrl);
    alert('📝 요약 버튼 클릭됨!');
    // TODO: 현재 탭의 URL을 텍스트 추출하는 곳으로 전송, 텍스트 추출하는 동안 추출 중 표시 
  };

  const handleTTS = () => {
    alert('🔊 TTS 실행!');
    // TODO: 요약된 텍스트를 TTS로 재생, 요약된 텍스트가 없으면 버튼 비활성화
  };

  // TODO: 글자 크기 변경 기능 추가/ 색깔 테마 변경 기능 추가 


  return (
    <main style={fontSizeStyle}>
      <h3>SidePanel Page</h3><div className="actions">
        <button className="action-button" onClick={handleSummarize}>
          📝 요약하기
        </button>
        <button className="action-button" onClick={handleTTS}>
          🔊 TTS 실행
        </button>
      </div>
      <h3>현재 탭 URL</h3>
            <p style={{ wordBreak: 'break-all' }}>{currentUrl}</p>
      
      {/* 하단 글자 크기 조절 버튼 */}
      <FontSizeToggle
        currentSize={fontSizeLevel}
        onChange={setFontSizeLevel}
      />
      <a href={link} target="_blank">
        generated by create-chrome-ext
      </a>
    </main>
  )
}

export default SidePanel
