import styled from 'styled-components'
import FontSizeToggle from '../components/FontSizeToggle'
import { fontSizeMap } from '../constants/fontSizes'
import { SummaryBox } from '../components/SummaryBox'
import { useCurrentTabUrl } from '../hooks/useCurrentTabUrl'
import { useGptSummary } from '../hooks/useGptSummary'
import { useState } from 'react'

const Container = styled.main`
  text-align: center;
  padding: 1em;
  margin: 0 auto;
  font-size: 1.25rem;
  line-height: 1.6;
`

const Title = styled.h3`
  color: #61dafb;
  text-transform: uppercase;
  font-size: 1.4em;
  font-weight: 500;
  line-height: 1.3;
  margin: 2rem auto;
`

const UrlText = styled.p`
  word-break: break-all;
  font-size: 1rem;
`

const Actions = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 2rem 0;
  gap: 1rem;
`

const Button = styled.button`
  background-color: #007acc;
  color: white;
  border: none;
  border-radius: 0.5rem;
  padding: 0.8em 1.5em;
  font-size: 1em;
  cursor: pointer;
  width: 85%;
  max-width: 300px;
  transition: background-color 0.2s ease-in-out;

  &:hover {
    background-color: #005999;
  }

  &:focus {
    outline: 3px solid #ffffff;
    outline-offset: 2px;
  }
`

const StyledLink = styled.a`
  font-size: 0.8em;
  margin: 0.5rem;
  color: #cccccc;
  text-decoration: none;

  &:hover {
    color: #61dafb;
  }
`

export const SidePanel = () => {
  const currentUrl = useCurrentTabUrl()
  const { summary, showSummary, fetchSummaryFromStorage, speakSummary } = useGptSummary()
  const [fontSizeLevel, setFontSizeLevel] = useState('medium')

  return (
    <Container style={{ fontSize: fontSizeMap[fontSizeLevel] }}>
      <Title>FISA Extension</Title>

      <Actions>
        <Button onClick={fetchSummaryFromStorage}>📝 요약하기</Button>
        <Button onClick={speakSummary}>🔊 TTS 실행</Button>
      </Actions>

      <Title>현재 탭 URL</Title>
      <UrlText>{currentUrl}</UrlText>

      {showSummary && summary && <SummaryBox title={summary.title} summary={summary.summary} />}

      <FontSizeToggle currentSize={fontSizeLevel} onChange={setFontSizeLevel} />

      <StyledLink
        href="https://github.com/guocaoyi/create-chrome-ext"
        target="_blank"
        rel="noreferrer"
      >
        generated by create-chrome-ext
      </StyledLink>
    </Container>
  )
}

export default SidePanel
